baseURL = "https://rubiefawn.me"
languageCode = "en-US"
title = "rubiefawn.me"
theme = "saffron"
capitalizeListTitles = false
enableRobotsTXT = true

[markup]
[markup.highlight]
style = 'base16-snazzy'

[markup.goldmark.renderer]
unsafe = true
